export const HASH_DOMAINS = {
  build: "agent-build/v1",
  root: "agent-root/v1",
  fact: "agent-fact/v1",
  payload: "payload/v1",
  occurrence: "source-occurrence/v1",
  evidence: "evidence/v1",
  emission: "emission/v1",
  environment: "environment-snapshot/v1",
  truthSnapshot: "truth-snapshot/v1",
  projectionPlan: "projection-plan/v1",
  providerRequest: "provider-request/v1",
  endpoint: "endpoint-contract/v1",
  modelOutcome: "model-outcome/v1",
  capabilityOutcome: "capability-outcome/v1",
  pending: "pending-trigger/v1",
  pendingRejected: "pending-rejected/v1",
  policy: "policy/v1",
  implementation: "implementation/v1",
  disposition: "disposition/v1",
  localDecision: "local-decision/v1",
  transformation: "transformation/v1",
} as const;

export type HashDomain = (typeof HASH_DOMAINS)[keyof typeof HASH_DOMAINS];
